// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsDY_gAA18IC01tt4jv9trbcg95Av_grc',
    appId: '1:820919275603:web:c69611b65ead363add36a6',
    messagingSenderId: '820919275603',
    projectId: 'asshop-3f053',
    authDomain: 'asshop-3f053.firebaseapp.com',
    storageBucket: 'asshop-3f053.appspot.com',
    measurementId: 'G-F9H9N4WCMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAQVQsQsN6g2xDQZId-u7eKX5ElhCTM0s',
    appId: '1:820919275603:android:f6295f67e6625802dd36a6',
    messagingSenderId: '820919275603',
    projectId: 'asshop-3f053',
    storageBucket: 'asshop-3f053.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCBMbUXtBEDU86WbvguthAJ1w6yYRDsSw',
    appId: '1:820919275603:ios:23ff7dd7d1cf7993dd36a6',
    messagingSenderId: '820919275603',
    projectId: 'asshop-3f053',
    storageBucket: 'asshop-3f053.appspot.com',
    iosClientId: '820919275603-8pf5070t49re6t742c2iun2c5osu96km.apps.googleusercontent.com',
    iosBundleId: 'com.aditya.asShop',
  );
}
